# Generated by Django 4.1.7 on 2023-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(default="hmffjw", max_length=6),
        ),
    ]
