# Generated by Django 4.1.7 on 2023-03-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_remove_team_members_team_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="images",
            new_name="image",
        ),
    ]
