# Generated by Django 4.1.7 on 2023-04-10 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0002_team_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="member",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
