# Generated by Django 4.1.7 on 2023-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_rename_images_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.CharField(default="jbqvba", max_length=6),
        ),
    ]
