# Generated by Django 4.1.7 on 2023-03-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0004_team_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(default="dkwjqs", max_length=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
