# Generated by Django 4.1.7 on 2023-03-07 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0005_alter_team_code_alter_team_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(default="qoblhq", max_length=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
