# Generated by Django 4.1.7 on 2023-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0006_alter_team_code_alter_team_leader_alter_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(default="wwzmmb", max_length=6),
        ),
    ]
