# Generated by Django 4.1.7 on 2023-03-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_alter_team_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(default="whmqwq", max_length=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/team_images/team.jgp",
                null=True,
                upload_to="static/images/team_images/",
            ),
        ),
    ]
