# Generated by Django 4.1.7 on 2023-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
