# Generated by Django 4.1.7 on 2023-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default="static/images/user_images/default.png",
                upload_to="static/images/user_images/",
            ),
        ),
    ]
