# Generated by Django 4.1.7 on 2023-03-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/user_images/default.png",
                null=True,
                upload_to="static/images/user_images/",
            ),
        ),
    ]
